### ISSUE TITLE
Different authors returned in result

### ISSUE THREAD

**Issue by ppolischuk** [CrossRef/cr-search#25]
http://search-staging.crossref.org/?q=Palmer+ontologies+publishing

For the result titled "Philosophy at Manchester Grammar School" Carfax Publishing is included in the author list in production but is missing in staging. There is also a hanging comma after "Michael Palmer" in staging, which seems to indicate some kind of anomaly.

<img width="1318" alt="staging-1100" src="https://user-images.githubusercontent.com/1800004/43781696-5da96c50-9a12-11e8-89c0-df3276718d09.png">

<img width="1317" alt="production-1100" src="https://user-images.githubusercontent.com/1800004/43781701-5f361bea-9a12-11e8-81d2-2a444b3217aa.png">

**Comment by eshadatta-crossref** [comment]
@ppolischuk , same as #24 . I don't see the discrepancy now. There might not have been equivalent data or something?

**Comment by ppolischuk** [comment]
Confirmed this is no longer reproducible. Closing.

**Comment by eshadatta-crossref** [comment]
Fixed in staging. http://search-staging.crossref.org/?q=Palmer+ontologies+publishing

**Comment by ppolischuk** [comment]
Confirmed working properly in production.
