### ISSUE TITLE
facet category names not consistent with production

### ISSUE THREAD

**Issue by ppolischuk** [CrossRef/cr-search#27]
The names of the facet categories on the left-hand side of the metadata search results pages are not consistent with production.

http://search-staging.crossref.org/?q=Palmer+ontologies+publishing

Prod: Type, Year, Publication, Category, Publisher, Funder name, Source
Staging: TYPE-NAME, PUBLISHED, CONTAINER-TITLE, PUBLISHER-NAME, FUNDER-NAME

**Acceptance Criteria**
Facet category names match those in production, where possible.

- TYPE-NAME should be TYPE
- PUBLISHED should be YEAR
- CONTAINER-TITLE should be PUBLICATION
- PUBLISHER-NAME should be PUBLISHER
- FUNDER-NAME should be FUNDER NAME

Note: Source is a facet category in production but does not appear to be useful and can be left off.
Category is used in production but may not be available via the REST API

**Comment by eshadatta-crossref** [comment]
same thing found as in #25 and #24. The data seems to have been fixed.

**Comment by ppolischuk** [comment]
Confirmed this is no longer reproducible. Closing.

**Comment by eshadatta-crossref** [comment]
@gbilder , please let me know if you wanted category? For some reason, I thought we had a conversation where you didn't want it in the facets. Please let me know if that is actually the case. Thanks so much.

**Comment by gbilder** [comment]
We do not want category. It is misleading for two reasons:

a. It applies to the journal level- not the article level. It shouldn't be in the article metadata at all.
b. It is only applied to *some* journal titles, those that have been categorised by Scopus.

**Comment by eshadatta-crossref** [comment]
@ppolischuk ,

This is now deployed to staging with the renamed headings. http://search-staging.crossref.org/?q=Palmer+ontologies+publishing

**Comment by ppolischuk** [comment]
Looking good in prod.
