### ISSUE TITLE
Unable to access pages > 10 in search results

### ISSUE THREAD

**Issue by ppolischuk** [CrossRef/cr-search#34]
When paging through very large result sets, I am unable to get past page 10 via the UI:

[https://search-staging.crossref.org/?q=cancer&page=10#](https://search-staging.crossref.org/?q=cancer&page=10#)
<img width="1783" alt="screen shot 2019-02-07 at 9 43 58 am" src="https://user-images.githubusercontent.com/1800004/52431365-eb375100-2abc-11e9-8591-24541ef3f694.png">

...or via the URL:

[https://search-staging.crossref.org/?q=cancer&page=15#](https://search-staging.crossref.org/?q=cancer&page=15#) produces the same results as [https://search-staging.crossref.org/?q=cancer&page=10#](https://search-staging.crossref.org/?q=cancer&page=10#)

**Comment by eshadatta-crossref** [comment]
Hey @ppolischuk ,

This seems to be a bug in production code as well! I can replicate the same bug here: https://search.crossref.org/?q=cancer&page=10#

Regardless, I'll investigate. 😃

**Comment by ppolischuk** [comment]
Good catch! Forgot to compare behavior in production. Who knows how long that's been the behavior so if it comes to it, we could push the new version to prod then fix this when we're able.

**Comment by eshadatta-crossref** [comment]
Monkey patch alert. I'll look into this later. Notes for my future self.
The will-paginate gem paginates in this system. The file: `lib/bootstrap.rb` has some functions that are overriding the default behavior of the gem. There seems to be a minimum set by this: `page = [query_page, 10].min`
